name: Generate Electron builds
on:
  release:
    types:
      - created
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master", "dev*" ]

jobs:

  release:
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            npm-task: "app:linuxbuild"
          - os: "windows-latest"
            npm-task: "app:winbuild"

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2       
    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Build electron app (linux)
      run: export GH_TOKEN=${{ secrets.GITHUB_TOKEN }} && npm run ${{ matrix.npm-task }}
      if: runner.os == 'Linux'
    - name: Build electron app (windows)
      run: powershell "[Environment]::SetEnvironmentVariable('GH_TOKEN','${{ secrets.GITHUB_TOKEN }}','User'); npm run ${{ matrix.npm-task }}"
      if: runner.os == 'Windows'
    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: HiCT trunk build
        path: |
          release/*/*.AppImage
          release/*/*.zip
          release/*/*.exe
          !release/**/*.yml
