name: Generate Electron builds
on:
  release:
    types:
      - created
  push:
    branches: ["master"]
    tags:
      - "v*"
  pull_request:
    branches: ["master", "dev*"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            npm-task: "app:linuxbuild"
            artifact-name: "linuxbuild"
          - os: "windows-latest"
            npm-task: "app:winbuild"
            artifact-name: "winbuild"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build electron app (linux)
        run: export GH_TOKEN=${{ secrets.GITHUB_TOKEN }} && npm run ${{ matrix.npm-task }}
        if: runner.os == 'Linux'
      - name: Build electron app (windows)
        run: powershell "[Environment]::SetEnvironmentVariable('GH_TOKEN','${{ secrets.GITHUB_TOKEN }}','User'); npm run ${{ matrix.npm-task }}"
        if: runner.os == 'Windows'
      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hict_trunk_build_${{ matrix.artifact-name }}
          path: |
            release/*/*.AppImage
            release/*/*.zip
            release/*/*.exe
            !release/**/*.yml

  release:
    runs-on: "ubuntu-latest"
    needs: ["build"]
    steps:
      - name: Prepare linux release
        uses: actions/download-artifact@v3
        with:
          name: hict_trunk_build_linuxbuild
      - name: Prepare windows release
        uses: actions/download-artifact@v3
        with:
          name: hict_trunk_build_winbuild
      - name: List available files
        run: ls -al
      - name: Generate latest release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Latest autogenerated build"
          files: |
            **/*.zip
            **/*.exe
            **/*.AppImage
